#!/bin/bash
# My first script

echo "Starting"
for i in 2 3 4 5 6 7 8 9 10
do
   echo "Simulating $i users."
   ./waf --run "scratch/wifiscenario --nWifi=$i --tracing=false --verbose=0"
   ./waf --run "scratch/wifiscenario --nWifi=$i --tracing=false --verbose=0"
   ./waf --run "scratch/wifiscenario --nWifi=$i --tracing=false --verbose=0"
   ./waf --run "scratch/wifiscenario --nWifi=$i --tracing=false --verbose=0"
   ./waf --run "scratch/wifiscenario --nWifi=$i --tracing=false --verbose=0"
done
