#!/bin/bash
# My first script

echo "Starting"
i=-2
j=-2
echo $i
for idx in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 33 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50
do
	echo "Simulating X-pos $i"
	echo "Simulating Y-pos $j"
        echo "Iteration $idx from 50"
	./waf --run "scratch/wifiscenario --nWifi=21 --APposx=$i --APposy=$j --tracing=false --verbose=0 --info=false"
	
done


i=3
j=-2
for idx in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 33 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50
do
	echo "Simulating X-pos $i"
	echo "Simulating Y-pos $j"
        echo "Iteration $idx from 50"
	./waf --run "scratch/wifiscenario --nWifi=21 --APposx=$i --APposy=$j --tracing=false --verbose=0 --info=false"
	
done

i=3
j=4
for idx in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 33 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50
do
	echo "Simulating X-pos $i"
	echo "Simulating Y-pos $j"
        echo "Iteration $idx from 50"
	./waf --run "scratch/wifiscenario --nWifi=21 --APposx=$i --APposy=$j --tracing=false --verbose=0 --info=false"
	
done
./meancalcPOS3.m





