#!/bin/bash
# My first script
clear
echo "Starting"
for i in 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21
do
   echo "Simulating $i users."
   for j in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
   do
   	./waf --run "scratch/mbpswifi --nWifi=$i --tracing=false --verbose=0 --info=false"
   done
done

./meancalc.m

